export const getMostRecentOrdersQuery = (customerId: string) => `
  SELECT
    ORDERS.ORDERID,
    ORDERS.ORDERDATE,
    ORDERS.DELIVERYEXPECTED,
    ORDERS.CONTAINSGIFT,
    ORDERITEMS.QUANTITY,
    ORDERITEMS.PRICE,
    PRODUCTS.PRODUCTNAME
  FROM
    ORDERS,
    ORDERITEMS,
    PRODUCTS
  WHERE
    ORDERS.ORDERID = ORDERITEMS.ORDERID AND
    ORDERITEMS.PRODUCTID = PRODUCTS.PRODUCTID AND
    ORDERS.CUSTOMERID = N'${customerId}'
`;
